name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.HZIEE }}
        TARGET_REPO: sonderlau/sonderlau.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn install && npm run docs:build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: hziee.site
