name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: sergioramos/yarn-actions/install@v6
        with:
          frozen-lockfile: true

      - uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://ftB.cname-cdn.com:1041/wwwroot/
          ftp-username: sonderlau
          ftp-password: ${{ secrets.FTP_PW }}
          local-dir: docs/.vuepress/dist/ 
          git-ftp-args: --insecure # if your certificate is setup correctly this can be removed
