name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install 
      
      - name: git status
        run: git status -uno --porcelain

      - name: reset Lock files
        run: run git checkout yarn.lock
        
      - uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftp://ftB.cname-cdn.com:1041/wwwroot/
          ftp-username: sonderlau
          ftp-password: ${{ secrets.FTP_PW }}
          local-dir: docs/.vuepress/dist/ 
          git-ftp-args: --insecure # if your certificate is setup correctly this can be removed
