name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Build Project
      run: |
        yarn install
        yarn run docs:build 

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp://ftb.cname-cdn.com:1016/web/
        ftp-username: sonderlau
        ftp-password: ${{ secrets.FTP_PW }}
        local-dir: docs/.vuepress/dist
