name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Build Project
      run: |
            yarn
            yarn run docs:build 
        
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ftp://ftB.cname-cdn.com:1041
        user: sonderlau
        password: ${{ secrets.FTP_PW }}
        localDir: "docs/.vuepress/dist"
        remoteDir: "wwwroot"
